[project]
name = "pons"
version = "0.2.0"
description = "Async RPC client for Ethereum"
authors = [
    {name = "Bogdan Opanchuk", email = "bogdan@opanchuk.net"},
]
dependencies = [
    "trio>=0.19.0",
    "httpx>=0.22",
    "eth-account>=0.5",
    "eth-utils>=1.10",
    "eth-abi>=2",
    "setuptools", # required by eth-utils, but it just assumes that it's already installed
]
requires-python = ">=3.8"
license-expression = "MIT"

[project.urls]
homepage = "https://github.com/fjarri/pons"

[project.optional-dependencies]
dev = [
    "pytest>=6",
    "pytest-trio",
    "pytest-cov",
    "py-solc-x>=1",
    # eth-tester only has pre-releases, so we can't set a range.
    # Another option is to pin it, but it has to be compatible
    # with eth-* stuff in the main dependencies.
    # TODO: make our own mock around Pyevm.
    "eth-tester[pyevm]",
]
docs = [
    "sphinx>=4",
    "furo",
    "sphinxcontrib-trio",
]

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
