[project]
name = "pons"
version = "0.1.0"
description = "Async RPC client for Ethereum"
authors = [
    {name = "Bogdan Opanchuk", email = "bogdan@opanchuk.net"},
]
dependencies = [
    "trio>=0.19.0",
    "httpx>=0.22",
    "eth-account>=0.5",
    "eth-utils>=1.10",
    "eth-abi>=2",
    "py-solc-x>=1",
    # Stupid eth-tester only has pre-releases, so we can't set a range.
    # Another option is to pin it, but it's a library, so let's hope tests will catch whatever.
    # TODO: make our own mock around Pyevm.
    "eth-tester[pyevm]",
]
requires-python = ">=3.8"
license = {text = "MIT"}

[project.urls]
homepage = "https://github.com/fjarri/pons"

[project.optional-dependencies]
dev = [
    "pytest>=6",
    "pytest-trio",
    "pytest-cov",
]
docs = [
    "sphinx>=4",
    "furo",
]

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
